" do not worry about vi compatibility
set nocompatible

set encoding=utf-8 " Necessary to show Unicode glyphs

" Comments lead with a double quote
" turn on color highlighting
syntax enable
" turn on relative line numbering
set relativenumber
" turn on mouse for all modes
set mouse=a

set hlsearch

function! s:DiffWithSaved()
  let filetype=&ft
  diffthis
  vnew | r # | normal! 1Gdd
  diffthis
  exe "setlocal bt=nofile bh=wipe nobl noswf ro ft=" . filetype
endfunction
com! DiffSaved call s:DiffWithSaved()

set clipboard=unnamed

" initialize all of the plugins managed by pathogen
execute pathogen#infect()

nmap <F8> :TagbarToggle<CR>

" TAGBAR configuration
" --------------------
let g:tagbar_singleclick = 1
autocmd VimEnter * nested :call tagbar#autoopen(1)
autocmd FileType * nested :call tagbar#autoopen(0)
" :autocmd BufEnter * nested :call tagbar#autoopen(0)

set background=dark " solarized dark background
colorscheme solarized " solarized color scheme
set t_Co=16 " mac vim sets up 256 color, the 16 palette should be chosen from solarized Terminal app

set backspace=indent,eol,start " backspace will delete anything
set title " change the title of the terminal window to the file being edited
set undofile     " creates an undo file so you can undo after closing and reopening a file
set nobackup            " do not create a backup (we are using the undo file)
set noswapfile          " do not create a swapfile

" navigate wrapped lines as if they were wrapped
 nnoremap j gj
 nnoremap k gk
" faster command entry
 nnoremap ; :
"

" http://vim.wikia.com/wiki/Converting_tabs_to_spaces
set expandtab " expand tabs into spaces as you come across them
set tabstop=4 " use 4 spaces for tabs
set shiftwidth=4 " when indenting, use multiple of 4 spaces
set shiftround " round off indenting to multiples of shiftwidth
set copyindent " new lines inherit the current indent (and maybe contextual, not sure)
set softtabstop=4 " backspace over space indentation will delete the indendation
set smarttab

set complete=t " only complete tags instead of buffer, and stuff, makes ctrl-p/n usable
set completeopt=longest,menuone,preview " show only matches so far, and show menu even if only one choice
set pumheight=7

filetype plugin indent on " load java/c/etc. standard plugin and indentation rules
set autoread " automatically re-read files that have changed
autocmd CursorHold,CursorHoldI * checktime " if user pauses typing for 'updatetime' seconds (4), check for file modification

set printoptions=paper:letter,duplex:off " Setup print options for hardcopy command.
set showcmd " some extra info about the currnt command at the last line of screen

" Allow left/right movement keys to "wrap" to the previous/next line.
" b - backspace key
" s - space key
" [ - left arrow  (insert and replace modes)
" ] - right arrow (insert and replace modes)
set whichwrap=b,s,[,]
set nostartofline " on large scale navigation, do not move to beginning of line

set wrapscan " wrap around buffer when searching
set incsearch " incremental searching - works well with highlighting
set ignorecase " do not match case
set smartcase " if you do type upper case anywhere, then it is case sensitive
"
" ignore these files for completion
set wildignore=*.swp,*.bak,*.class,*.o,*.jar,*.gif,*.jpg,*.png,*.bmp,*.svn-base,*/svn/*


" use tabs/windows keep those edited buffers around
set hidden " can hide buffers even if there is an edit
set tag=./tags;$HOME,tags,$HOME " stop search above home directory

let mapleader=","

" always show the powerline, and use unicode symbols
set laststatus=2
let g:Powerline_symbols = 'unicode'
let g:Powerline_colorscheme='powerline_solarized_dark_16'


" tagbar configuration if you install it
" ---------------------------------------
" one mouse click navigates
let g:tagbar_singleclick = 1

" open tabgar if file type supports it
autocmd VimEnter * nested :call tagbar#autoopen(1)

" open tagbar on supported file types for new editors within vim
autocmd FileType * nested :call tagbar#autoopen(0)

" open tagbar with new tab for supported file type, might be disabled because over aggressive? I forgot
" :autocmd BufEnter * nested :call tagbar#autoopen(0)

" map F8 to open/close the tagbar
nmap <F8> :TagbarToggle<CR>
autocmd vimenter * if !argc() | NERDTree | wincmd p | endif
map <C-n> :NERDTreeToggle<CR>
" autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
let NERDTreeShowBookmarks=1
let NERDTreeIgnore=['\.class$', '^CVS$', '\~$']
" need this off to use netrw which is the only way to get VCSCommand to work across directories
let NERDTreeHijackNetrw=0

let g:EclimSignLevel=2 " only mark errors instead of a bazillion warnings
nmap <F3> :JavaSearchContext<CR>
let g:EclimCompletionMethod='omnifunc'   " also required for eclim to work

let g:ctrlp_follow_symlinks = 1 " follow symlinks but avoid loops
let g:ctrlp_max_files = 40000 " default only 10000

map <Leader>mbe :MBEOpen<cr>
map <Leader>mbc :MBEClose<cr>
map <Leader>mbt :MBEToggle<cr>

hi MBENormal               ctermbg=black ctermfg=white
hi MBEChanged              ctermbg=black ctermfg=yellow
hi MBEVisibleNormal        ctermbg=black ctermfg=white cterm=bold
hi MBEVisibleChanged       ctermbg=black ctermfg=yellow cterm=bold
hi MBEVisibleActiveNormal  ctermbg=white ctermfg=black cterm=bold
hi MBEVisibleActiveChanged ctermbg=yellow ctermfg=black cterm=bold

