" do not worry about vi compatibility
set nocompatible

set encoding=utf-8 " Necessary to show Unicode glyphs

" Comments lead with a double quote
" turn on color highlighting
syntax enable
" turn on relative line numbering
"set relativenumber
" turn on line numbering
set number

" turn on mouse for all modes
set mouse=a
set clipboard=unnamed
set hlsearch
set backspace=indent,eol,start " backspace will delete anything
set undofile     " creates an undo file so you can undo after closing and reopening a file
set title " change the title of the terminal window to the file being edited
set nobackup            " do not create a backup (we are using the undo file)
set noswapfile          " do not create a swapfile
" navigate wrapped lines as if they were wrapped
 nnoremap j gj
 nnoremap k gk
" faster command entry
 nnoremap ; :
let mapleader=","
"
" set complete=t " only complete tags instead of buffer, and stuff, makes ctrl-p/n usable
set complete=.,i,t      " scan current file, included files (super classes and interfaces), and then ctags
set pumheight=7
set completeopt=longest,menuone,preview " show only matches so far, and show menu even if only one choice

" http://vim.wikia.com/wiki/Converting_tabs_to_spaces
set expandtab " expand tabs into spaces as you come across them
set tabstop=4 " use 4 spaces for tabs
set shiftwidth=4 " when indenting, use multiple of 4 spaces
set shiftround " round off indenting to multiples of shiftwidth
set copyindent " new lines inherit the current indent (and maybe contextual, not sure)
set softtabstop=4 " backspace over space indentation will delete the indendation
set smarttab

filetype plugin indent on " load java/c/etc. standard plugin and indentation rules
set autoread " automatically re-read files that have changed
autocmd CursorHold,CursorHoldI * checktime " if user pauses typing for 'updatetime' seconds (4), check for file modification

" Allow left/right movement keys to "wrap" to the previous/next line.
" b - backspace key
" s - space key
" [ - left arrow  (insert and replace modes)
" ] - right arrow (insert and replace modes)
set whichwrap=b,s,[,]
set nostartofline " on large scale navigation, do not move to beginning of line

set wrapscan " wrap around buffer when searching
set incsearch " incremental searching - works well with highlighting
set ignorecase " do not match case
set smartcase " if you do type upper case anywhere, then it is case sensitive
"
" ignore these files for completion
set wildignore=*.swp,*.bak,*.class,*.o,*.jar,*.gif,*.jpg,*.png,*.bmp,*.svn-base,*/svn/*


" use tabs/windows keep those edited buffers around
set hidden " can hide buffers even if there is an edit
set tag=./tags;$HOME,tags,$HOME " stop search above home directory


function! s:DiffWithSaved()
  let filetype=&ft
  diffthis
  vnew | r # | normal! 1Gdd
  diffthis
  exe "setlocal bt=nofile bh=wipe nobl noswf ro ft=" . filetype
endfunction
com! DiffSaved call s:DiffWithSaved()


" initialize all of the plugins managed by pathogen
execute pathogen#infect()


" TAGBAR configuration
" --------------------
" map F8 to open/close the tagbar
nmap <F8> :TagbarToggle<CR>
let g:tagbar_singleclick = 1
let g:ctrlp_max_files = 40000 " default only 10000 though this takes a while to process
" open tabgar if file type supports it
" autocmd VimEnter * nested :call tagbar#autoopen(1)
" open tagbar on supported file types for new editors within vim
" autocmd FileType * nested :call tagbar#autoopen(0)
" open tagbar with new tab for supported file type, might be disabled because over aggressive? I forgot
" :autocmd BufEnter * nested :call tagbar#autoopen(0)


set background=dark " solarized dark background
let g:solarized_termcolor=256
colorscheme solarized " solarized color scheme

set printoptions=paper:letter,duplex:off " Setup print options for hardcopy command.
set showcmd " some extra info about the current command at the last line of screen


" vim-airline statusline always present
set laststatus=2


autocmd vimenter * if !argc() | NERDTree | wincmd p | endif
map <C-n> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
let NERDTreeShowBookmarks=1
let NERDTreeIgnore=['\.class$', '^CVS$', '\~$']
" need this off to use netrw which is the only way to get VCSCommand to work across directories
let NERDTreeHijackNetrw=0

let g:EclimSignLevel=2 " only mark errors instead of a bazillion warnings
nmap <F3> :JavaSearchContext<CR>
let g:EclimCompletionMethod='omnifunc'   " also required for eclim to work

let g:ctrlp_follow_symlinks = 1 " follow symlinks but avoid loops
let g:ctrlp_max_files = 40000 " default only 10000

map <Leader>mbe :MBEOpen<cr>
map <Leader>mbc :MBEClose<cr>
map <Leader>mbt :MBEToggle<cr>

hi MBENormal               ctermbg=black ctermfg=white
hi MBEChanged              ctermbg=black ctermfg=yellow
hi MBEVisibleNormal        ctermbg=black ctermfg=white cterm=bold
hi MBEVisibleChanged       ctermbg=black ctermfg=yellow cterm=bold
hi MBEVisibleActiveNormal  ctermbg=white ctermfg=black cterm=bold
hi MBEVisibleActiveChanged ctermbg=yellow ctermfg=black cterm=bold

au BufNewFile,BufRead *.ad setlocal ft=asciidoc

let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:syntastic_rust_checkers = ['rustc']

let g:indent_guides_enable_on_vim_startup = 1
autocmd FileType python nnoremap <leader>y :0,$!yapf<Cr>

let g:python_pep8_indent_multiline_string = 1

let g:racer_experimental_completer = 1

let g:ycm_rust_src_path = '/home/plockc/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src'
